yushu/User/urls.py
from django.urls import path, include
from .views import *

app_name = 'User'

urlpatterns = [
    path('', index, name='index'),  # 首页
    # path('/<int:page>', index, name='index'),  # 首页分页
    path('head_photo/', head_photo, name='head_photo'),
    path('search/', search, name='search'),  # 搜索
    # path('search/<int:page>/', search, name='search'),  # 搜索分页

    path('refresh/', captcha_refresh, name='captcha-refresh'),  # 动态生成验证码
    path('login/', login, name='login'),  # 登录
    path('register/', register, name='register'),  # 注册
    path('logout/', logout, name='logout'),  # 退出
    path('detail/', detail, name='detail'),  # 书内容
    path('detail/', detail, name='detail'),  # 书内容
    path('personal/', personal, name='personal'),  # 个人资料
    path('password/', password, name='password'),  # 改密
    path('send_emails/', send_emails, name='send_emails'),  # 发邮件

    path('add_gifts/', add_gifts, name='add_gifts'),  # 添加赠送
    path('add_wish/', add_wish, name='add_wish'),  # 添加心愿
    path('gifts_list/', gifts_list, name='gifts_list'),  # 赠送清单
    path('wish_list/', wish_list, name='wish_list'),  # 心愿清单
    path('pending_list/', pending_list, name='pending_list'),  # 鱼漂清单
    path('pending_repeal/', pending_repeal, name='pending_repeal'),  # 鱼漂清单撤销
    path('repeal/', repeal, name='repeal'),  # 撤销
    path('order/', order, name='order'),  # 订单
    path('give/', give, name='give'),  # 向他赠送此书
    path("pay/", pay, name='pay'),
    # path("check_pay/", check_pay, name='check_pay'),

]

yushu/yushu/urls.py
from django.contrib import admin
from django.urls import path, include

from User import views
#
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', views.index,),

    path('app/', include('User.urls', namespace='app')),
    path('admin/', include('Admin.urls', namespace='admin')),
    path('captcha', include('captcha.urls',)),
]

yushu/User/forms.py
from django import forms
from captcha.fields import CaptchaField

class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label='验证码')


class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender,)
    captcha = CaptchaField(label='验证码')

yushu/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html>


<title>鱼书</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

{% block css %}

{% endblock css %}
<body>

{% block quanbu %}


<div class="nav-self">
    <div style="padding-top: inherit" class="container">
        <form class="form-inline" action="{% url 'app:search' %}" method="get">
{#        {% csrf_token %}#}
            <div class="flex-vertical-center-height">
                <div class="col-md-2  col-xs-3 logo">
                    <img src="/static/images/logo-yushu.png"/>
                </div>
                <div style="margin-left:20px;" class="col-md-7  col-xs-6 input-group">
                    <input name="q" type="text" placeholder="ISBN、图书名称"
                           class="form-control input-sm">
                    <span class="input-group-btn">
                            <input class="btn btn-search" type="submit" value="搜索"/>
                        </span>
                </div>
                <div class="col-md-3 col-xs-3" style="padding-right: 0;width: 600px">

                    {% if request.session.is_login %}   
                        <div class="container-height flex-vertical-center login-box" >
                            <a href="{% url 'app:head_photo' %}"><img src="/static/{{ request.session.head_photo }}" title="头像" width="60px" style="border: 1px solid black;padding: 0px;margin: 0px"></a>
                            <a href="{% url 'app:personal' %}" >{{ request.session.user_name }}的鱼书</a> &emsp;
                            {% if user.usertype == 0 %}
                                <a href="{% url 'admin:index' %}" >管理员</a>
                            {% endif %}
                            <a class="btn-end" href="{% url 'app:logout' %}">注销</a>

                        </div>
                    {% else %}
                        <div class="container-height flex-vertical-center login-box">

                                <div style="height: 100%; width: 100%;display: flex; justify-content: flex-end; align-items: center">
                                    <a href="{% url 'app:login' %}">登录</a>
                                    <a class="btn-end" href="{% url 'app:register' %}">注册</a>
                                </div>

                        </div>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>
<div class="sub-nav flex-vertical-center">
    <div class="container" style="width: 100%">
        <div class="row">
            <div class="col-md-2 col-xs-3 col-md-offset-2">
                <a id="recent" href="/app/"
                   class="flex-vertical-hor-center">
                    <img src="/static/images/upload.png"/>
                    <span>最近上传</span>
                </a>
            </div>
            <div class="col-md-2 col-xs-3">
                <a id="gifts" href="/app/gifts_list"
                   class="flex-vertical-hor-center">
                    <img src="/static/images/gift.png"/>
                    <span>赠送清单</span>
                </a>
            </div>
            <div class="col-md-2 col-xs-3">
                <a id="wishes" href="/app/wish_list"
                   class="flex-vertical-hor-center">
                    <img src="/static/images/wish.png"/>
                    <span>心愿清单</span>
                </a>
            </div>
            <div class="col-md-2 col-xs-3">
                <a id="pending" href="/app/pending_list"
                   class="flex-vertical-hor-center">
                    <img src="/static/images/fish.png"/>
                    <span>鱼漂</span>
                </a>
            </div>
        </div>
    </div>
</div>



    
    

    
{% block content %}

{% endblock %}    
    
    
    
    
    

<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>

{% endblock quanbu %}
</body>
<script src="/static/js/aixin.js"></script>
{% block jss %}

{% endblock jss%}

</html>

yushu/templates/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css %}






    <link rel="stylesheet"
          href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="shortcut icon"
          href="/static/images/icon.png">

    <link rel="stylesheet" href="/static/css/remodal.css">
    <link rel="stylesheet" href="/static/css/remodal-default-theme.css">
    <link rel="stylesheet" href="/static/css/book-detail.css">
{% endblock %}


{% block content %}
    {% load staticfiles %}
    <div class='container'>
        <div class="row" id="alert">

            <div id="alert" class="alert alert-warning" role="alert">{{ msg }}</div>

        </div>


        <div class="row book-container my-detail-row" style="width: 100%">
            <div class="col-md-2">
                <img class="book-img" src="/static/upload/{{ content.image }}"/>
            </div>
            <div class="col-md-5 flex-vertical detail-con">
                <div>
                    <h4>{{ content.bname }}</h4>
                </div>
                <div class="description-font-margin">
                    <div>
                        <span>作者:</span>
                        <span>{{ content.author }}</span>
                    </div>
                    <div>
                        <span>出版社:</span>
                        <span>{{ content.publisher }}</span>
                    </div>
                    <div>
                        <span>出版年：</span>
                        <span>{{ content.pubdate }}</span>
                    </div>
                    <div>
                        <span>页数：</span>
                        <span>{{ content.pages }}</span>
                    </div>
                    <div>
                        <span>定价：</span>
                        <span>￥{{ content.price }}</span>
                    </div>
                    <div>
                        <span>精装：</span>
                        <span>{{ content.jingz }}</span>
                    </div>
                    <div>
                        <span>ISBN：</span>
                        <span id="isbn">{{ content.isbn }}</span>
                    </div>

                    <div class="color-count">
                        <span>{{ wuser | length }}人想要 / </span>
                        <span>{{ guser | length }}人可赠送</span>
                    </div>

                </div>
            </div>
        </div>
        <div style="margin-top:30px; display: flex" class="row ">
            {% if not isgifts and not idwish %}
                <div class="col-md-1">
                <span class="zengsong">
                <a class="btn btn-outline" href="#">
                        赠送此书
                </a></span>
                </div>
                <div style="margin-left:30px;" class="col-md-1">
                    <a class="btn btn-outline" href="#">
                        <span class="xinyuan">加入到心愿清单</span>
                    </a>
                </div>
            {% elif idwish %}
                <div class="col-md-3">
                    <span class="bg-info">已添加至心愿清单</span>
                </div>
            {% else %}
                <div class="col-md-3">
                    <span class="bg-info">已添加至赠送清单</span>
                </div>
            {% endif %}
        </div>
        <div style="margin-top: 30px;" class="row">
            <div class="col-md-2"><span class="description-title">内容简介</span></div>
        </div>
        <div style="margin-top:15px;" class="row">
            <div class="col-md-11">
                <p class="description-font">{{ content.intro }}</p>
            </div>
        </div>

        {% if  idwish.launched == 0 and  idwish %}
            <div style="margin-top:30px;" class="row">
                <div class="col-md-3"><span class="description-title">向他们请求此书</span></div>
            </div>
            <hr style="margin-top:5px;"/>
            {% for gift in guser %}
                <div style="margin-top:30px;" class="row">
                    <div class="col-md-1">
                        {{ gift.uid.name }}
                    </div>
                    <div class="col-md-2 description-font">
                        上传于{{ gift.date |date:"Y-m-d" }}
                    </div>
                    {% if gift.launched == 0 %}
                        <div class="col-md-2">
                        <span class="qingqiu">
                            <a class="btn-normal" href="{% url 'app:order' %}?id= {{ gift.id }}">
                            向他请求此书</a>
                        </span>
                        </div>
                    {% else %}
                        <div class="col-md-2">
                        <span >
                            <a class="btn-normal" href="#">
                            已向他请求此书</a>
                        </span>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}
        {% if isgifts.launched  == 0 and isgifts %}
            <div style="margin-top:30px;" class="row">
                <div class="col-md-3"><span class="description-title">向他们赠送此书</span></div>
            </div>
            <hr style="margin-top:5px;"/>
            {% for wish in wuser %}
                <div style="margin-top:30px;" class="row">
                    <div class="col-md-1">
                        {{ wish.uid }}
                    </div>
                    <div class="col-md-2 description-font">
                        上传于{{ wish.date |date:"Y-m-d" }}
                    </div>
                    {% if wish.launched == 0 %}
                        <div class="col-md-2">
                        <span class="sendwish">
                            <a class="btn-normal" href="{% url 'app:give' %}?id={{ wish.id }}" id="sendwish">
                            向他赠送此书</a>
                        </span>
                        </div>
                    {% elif wish.launched == 1 %}
                        <div class="col-md-2">
                        <span >
                            <a class="btn-normal" href="#">
                            已向他赠送此书</a>
                        </span>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        {% endif %}

        {#        <div class="remodal" data-remodal-id="modal" role="dialog"#}
        {#             aria-labelledby="modal1Title" aria-describedby="modal1Desc"#}
        {#             data-remodal-options="closeOnOutsideClick: false">#}
        {#            <button data-remodal-action="close" class="remodal-close"#}
        {#                    aria-label="Close"></button>#}
        {#            <div>#}
        {#                <h5 class="diag-title">#}
        {#                    您确定拥有《{{ content.bname }}》这本书吗？</h5>#}
        {#                <p id="modal1Desc" class="description-font">#}
        {#                    如果您不想赠送此书，或者没有这本书，请不要随意发布虚假信息。谢谢你的支持和理解。#}
        {#                </p>#}
        {#            </div>#}
        {#            <br>#}
        {#            <button data-remodal-action="confirm" class="remodal-confirm">确定赠送</button>#}
        {#            <button data-remodal-action="cancel" class="remodal-cancel">不，算了</button>#}
        {#        </div>#}

    </div>
{% endblock %}
{% block jss %}




    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/base.js"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>

    <script src="/static/js/remodal.min.js"></script>
    <script src="/static/js/book-detail.js"></script>
    <script>
        $(function () {
            {#$('.qingqiu').click(function () {#}
            {##}
            {#    alert("您确定拥有这本书吗？" +#}
            {#        "如果您不想赠送此书，或者没有这本书，请不要随意发布虚假信息。谢谢你的支持和理解。")#}
            {# });#}
            {#//zengsong  {id: '{{ book.id }}#}
            $('.zengsong').click(function () {
                $.getJSON('{% url 'app:add_gifts' %}?id={{ content.id }}', function (data) {
                    if (data.status == 2) {
                        alert('您还未登录，登录才能操作哦！！！')
                    } else if (data.status == 1) {
                        alert('这本书以添加进您的赠送清单或已经存在于您的心愿清单，请不要重复添加')
                    } else {
                        alert('添加成功！');
                        window.location.href = "{% url 'app:detail' %}?id={{ content.id }}"
                    }
                })
            });

            //xinyuan
            $('.xinyuan').click(function () {
                $.getJSON('{% url 'app:add_wish' %}', {id: '{{ content.id }}'}, function (data) {
                    if (data.status == 2) {
                        alert('您还未登录，登录才能操作哦！！！')
                    } else if (data.status == 1) {
                        alert('这本书以添加进您的赠送清单或已经存在于您的心愿清单，请不要重复添加')
                    } else {
                        alert('添加成功！');
                        window.location.href = "{% url 'app:detail' %}?id={{ content.id }}"

                    }
                })
            });

            {#//sendwish 向他赠送此书#}
            $('.sendwish').click(function () {
                alert('已向他/她发送了一封邮件，如果他/她愿意接受你的赠送，你将收到一个鱼漂');
            {#    $.getJSON('{% url 'app:give' %}', {id: '{{ wish.id }}'}, function (data) {#}
            {#        odiv = document.getElementById('alert');#}
            {#        odiv1 = document.getElementById('sendwish');#}
            {#        odiv.innerText = '已向他/她发送了一封邮件，如果他/她愿意接受你的赠送，你将收到一个鱼漂';#}
            {#        odiv.style.fontSize = '20px';#}
            {#        odiv.style.color = 'red';#}
            {#        odiv.style.background = '#E1E4E8';#}
            {##}
            {##}
            {#     })#}
             });
        });
    </script>

{% endblock %}

yushu/templates/gifts.html
{% extends 'base.html' %}
{% load fetchs %}


{% block css %}



    <link rel="stylesheet"
          href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="shortcut icon"
          href="/static/images/icon.png">

{% endblock %}

{% block content %}



    <div class='container'>
        <div class="row">


        </div>


        <div class="row flex-vertical-center">
            <div style="margin-top:20px;" class="col-md-6">
                <span class="sub-title">我想赠送的书籍  共 {{ lists | length }}  本</span>
                <hr>
            </div>
        </div>
        {% for bb in lists %}



            <div class="row my-gifts-row">
                <a href="{% url 'app:detail' %}?id={{ bb.bookid.id }}" class="">
                    <div style="margin-bottom:30px; display: flex; justify-content: space-between"
                         class="col-md-9 col-padding content-box">
                        <div style="display: flex; justify-content: flex-start; flex-grow: 1">
                            <div class="col-md-2 img-box">
                                <img class="book-img-small shadow" src="/static/upload/{{ bb.bookid.image }}">
                            </div>
                            <div style="margin-top:6px;" class="col-md-6 flex-vertical">
                            <span id="title"
                                  class="book-middle-title">{{ bb.bookid.bname }}</span>
                                <div style="margin-top:6px;"
                                     class="flex-vertical description-font">
                                    <span id="author">{{ bb.bookid.author }}</span>
                                    <span id="publisher">{{ bb.bookid.publisher }}</span>
                                    <span id="price">￥{{ bb.bookid.price }}元</span>
                                    <span id="isbn">{{ bb.bookid.isbn }}</span>
                                </div>
                                <a class="link-normal"
                                   href="{% url 'app:repeal' %}?id={{ bb.bookid.id }}">
                                    撤销
                                </a>
                            </div>
                        </div>
                        <div class="col-md-3 flex-vertical" style="padding: 0">

                            <a href="{% url 'app:detail' %}?id={{ bb.bookid.id }}">
                                <span class="bg-info">{{ bb.bookid.id | fetch:a }}人想要</span>

                            </a>

                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}


    </div>
{% endblock %}
{% block jss %}





    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/base.js"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>

    <script src="/static/js/util.js"></script>
    <script src="/static/js/search_result.js"></script>

{% endblock %}

yushu/templates/head_photo.html
{% extends 'base.html' %}
{% load static %}

{% block css %}



    <link rel="stylesheet"
          href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="shortcut icon"
          href="/static/images/icon.png">

    <link rel="stylesheet" href="/static/css/personal.css">

{% endblock %}


{% block quanbu %}
    <div class='container'>
        <div class="row">

            <div class="alert alert-warning" role="alert">{{ msg }}</div>
        </div>

        <div class="row">
            <div style="margin-top:150px;" class="col-md-6 col-md-offset-3">
                <div class="row">
                    <div class="col-md-2">
                        <a onclick="window.history.go(-1)" href="#">返回</a>
                    </div>
                    <div class="col-md-2">
                        <a  href="{% url 'app:index' %}">首页</a>
                    </div>
                </div>
                <div class="bg-container">
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4 text-center" style="margin: 1px">

                        <span class="big-title" style="margin: 1px 62px 1px 62px;width: 300px">
                            <a href="/static/{{ user.head_photo }}"><img src="/static/{{ user.head_photo }}"
                                                                      title="头像" width="60px"
                                                                      style="border: 1px solid black;padding: 0px;margin: 0px"></a>
                            {{ request.session.user_name }}
                        </span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 flex-vertical personal-detail">
                            <form action="{% url 'app:head_photo' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <h3>设置我的新头像</h3><br/>
                                <p><input name="pic" type="file" style="height:23px; width:300px;"/></p>
                                <p><input type="submit" value="保存"></p>


                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}
<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>
{% block jss %}




    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/base.js"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>


{% endblock %}

yushu/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block css %}


    <link rel="stylesheet"
          href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon"
          href="{% static 'images/icon.png' %}">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock css %}

{% block content %}


    <div class='container'>
        <div class="row">


        </div>

        <div class="row">
            <div class="col-md-12">
            </div>
        </div>
        <div id="books" class="row">
            {% for bb in pagination.object_list %}

                <div class="col-sm-4 book-container">
                    <a href="{% url 'app:detail' %}?id={{ bb.id }}" class="link">
                        {#  < a href="{% url 'book:bookdetail' %}?id={{ book.id }}" class="link">#}
                        <div class="col-md-4 no-padding">
                            <img class="book-img cssshadow" src="/static/upload/{{ bb.image }} ">
                        </div>
                        <div style="margin-left: 0;" class="col-md-8 flex-vertical book-info">
                            <span class="title">{{ bb.bname }}</span>
                            <div class="description-font"><span>作者：</span><span>{{ bb.author }}</span>
                            </div>
                            <span class="summary description-font">{{ bb.intro }}</span>
                        </div>
                    </a>
                </div>

            {% endfor %}


        </div>



        <nav aria-label="Page navigation">
              <ul class="pagination">
                {% if pagination.has_previous %}
                    <li>
                      <a href="{% url 'app:index' %}?page={{ pagination.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                 {% else %}
                    <li class="disabled">
                      <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                {% endif %}
                  {% for page in number %}
                      {% if page == pagination.number %}
                        <li class="active"><a href="{% url 'app:index' %}?page={{ page }}">{{ page }}</a></li>
                      {% else %}
                          <li><a href="{% url 'app:index'%}?page={{ page }}">{{ page }}</a></li>
                      {% endif %}
                  {% endfor %}

              {% if pagination.has_next  %}
                <li>
                  <a href="{% url 'app:index'%}?page={{  pagination.next_page_number  }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
              {% else %}
                  <li class="disabled">
                  <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
              {% endif %}
              </ul>
            </nav>


    </div>
{% endblock %}

<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>


{% block jss %}

    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/base.js"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>

{% endblock jss %}

yushu/templates/nodrift.html
{% extends 'base.html' %}

   {% block css %}





    <link rel="stylesheet"
          href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="shortcut icon"
          href="/static/images/icon.png">

 <link rel="stylesheet" href="/static/css/not-enough.css">

{% endblock %}
{% block content %}

<div class='container'>
    <div class="row">




    </div>

    <div style="margin-top:60px;" class="row">
        <div class="col-md-12 flex-vertical main-color">
            <span style="margin-bottom: 10px;" class="large-title">你没有足够的鱼豆或超过限制</span></span>
            <span>当前你有{{ beans }}个鱼豆</span>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <span class="main-color">
                温馨提示：每请求1本书，需要消耗1个鱼豆；当你已经请求两本书时，你必须先赠送1本书籍。
            </span>
        </div>
    </div>
    <div class="row">
        <div style="margin-top:50px;margin-bottom:30px;" class="col-md-3">
            <span class="description-font">以下是获取鱼豆的方式</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 bg">
            <span>1.  上传图书</span>
        </div>
        <div class="col-md-9 bg-opacity">
            <span>在搜索框内搜索书籍，并将书籍“加入到赠送清单” 即可获得0.5个鱼豆。务必确保你愿意赠送此书。</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 bg">
            <span>2.  赠送图书</span>
        </div>
        <div class="col-md-9 bg-opacity">
            <span>每成功赠送一本图书，我们将额外赠送你1个鱼豆。</span>
        </div>
    </div>

</div>
{% endblock %}
{% block jss %}




    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/base.js"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>

{% endblock %}

yushu/templates/password.html
{% extends 'base.html' %}



{% block css %}

    <link rel="stylesheet"
          href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="shortcut icon"
          href="/static/images/icon.png">

{% endblock %}

{% block quanbu %}




    <div class='container'>
        <div class="row">



            {% if msg %}
                <div class="alert alert-warning" role="alert">{{ msg }}</div>
            {% endif %}
        </div>

        <div class="row white-bg-margin">
            <div class="col-md-6 col-md-offset-3">
                <div class="col-md-2">
                    <a onclick="window.history.go(-1)" href="#">返回</a>
                </div>
                <div class="bg-container">

                    <div class="row">

                        <div class="col-md-4 col-md-offset-4 text-center">
                            <span class="big-title">鱼 书</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 flex-vertical input-margin">
                            <form action="{% url 'app:password' %}" method="post" id="form1">
                                {% csrf_token %}
                                <input id="old_password" name="old_password" type="password"
                                       placeholder="原密码"
                                       class="form-control none-input"/>
                                <input name="new_password1" type="password"
                                       placeholder="新密码"
                                       class="form-control none-input"/>
                                <input name="new_password2" type="password"
                                       placeholder="请确认新密码"
                                       class="form-control none-input"/>
                                <input name="email" type="text"
                                       placeholder="请输入邮箱"
                                       class="form-control none-input" value="{{ user.0.email }}" readonly/>
                                <input name="email_code" type="text"
                                       placeholder="请输入验证码"
                                       class=" none-input" style="width: 50%"/>
                                <button style="margin:5px;float: right;width: 40%;height: 34px">获取验证码</button>
                                <input style="margin-top:15px;clear: right" id="btn-submit"
                                       type="submit"
                                       class="btn btn-big btn-block" value="提交">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock %}
<div id="footer" class="flex-hor-center">
    <span>© 2017-2020 yushu.im created by 七月</span>
</div>



{% block jss %}


    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/base.js"></script>
    <script>
        $SCRIPT_ROOT = "";
    </script>
    <script>
        $('button').click(function (ev) {
            ev.preventDefault();
            $.post("{% url 'app:send_emails' %}", $('#form1').serialize())
        })
    </script>
{% endblock %}