Xforum/apps/views/admin.py
import os

from flask import Blueprint, render_template, session, Response, request, redirect, url_for

# from VerfiCode import VerfiCode
from sqlalchemy import func
from werkzeug.security import check_password_hash, generate_password_hash

from exts import photos
from settings import UPLOAD_DIR

admin = Blueprint('admin', __name__)
from apps.models.model import *


# 登录
@admin.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        return render_template('admin.html')
    else:
        print('11111111111111111111111111')
        username = request.form.get('username', None)
        password = request.form.get('password', None)

        # if username and password:
        #     user = User.query.filter(User.username == username).first()
        #     print('22222222222222222222')
        #     if user:
        #         result = check_password_hash(user.password, password)
        #         if result:
        #             # 服务器保存 session 当成字典
        #             session['adminname'] = username
        #             print('33333333333333333333')
        #             return redirect(url_for('admin.index'))
        #
        #         else:
        #             return render_template('admin.html')
        #     else:
        #         return render_template('admin.html')
        #
        # else:
        #     return render_template('admin.html')

        return redirect(url_for('admin.inde'))
# 首页
@admin.route('/inde')
def inde():
    return render_template('admin_index.html')

Xforum/apps/views/user_view.py
import os
import re

from flask import Blueprint, render_template, session, Response, request, redirect, url_for

# from VerfiCode import VerfiCode
from sqlalchemy import func
from werkzeug.security import check_password_hash, generate_password_hash

from exts import photos
from settings import UPLOAD_DIR

bbs = Blueprint('bbs', __name__)
from apps.models.model import *


# 首页
@bbs.route('/')
def index():
    # 大板块
    bz = BbsCategory.query.filter(BbsCategory.parentid == 0).all()
    # 小版块
    smallbz = BbsCategory.query.filter(BbsCategory.classpath > 0).all()
    # 得到最新注册用户名
    newuser = User.query.order_by(-User.uid).first()
    # 普通用户个数
    numberuser = User.query.count()
    # 帖子数
    numbertz = BbsDetails.query.filter(BbsDetails.first == 1).count()

    username = session.get('username', None)
    # print('llllllllll')
    # print(username)
    user = User.query.filter(User.username == username).first()
    if user:
        if user.udertype:
            utype = '普通用户'
        else:
            utype = '管理员'
    else:
        utype = ''
    # print(user)
    # print(username)
    # print('xixixiiiiiiiiii')
    return render_template('index.html', **{
        'category': bz,
        'smalls': smallbz,
        'newuser': newuser,
        'user': user,
        'utype': utype,
        'number': numberuser,
        'numbertz': numbertz
    })


# 帖子列表
@bbs.route('/list/<int:id>')
def list(id):
    # 所有大板块
    dbk = BbsCategory.query.filter(BbsCategory.parentid == 0).all()
    # 所有小版块
    xbk = BbsCategory.query.filter(BbsCategory.parentid == 1).all()
    # 取ID的小版块
    idxbk = BbsCategory.query.filter(BbsCategory.cid == id).all()
    # 取ID的小版块的帖子数量
    tzs = BbsDetails.query.filter(BbsDetails.classid == id).count()
    # 帖子
    tz = BbsDetails.query.filter(BbsDetails.classid == id, BbsDetails.first == 1).all()
    # 得到最新注册用户名
    newuser = User.query.order_by(-User.uid).first()
    # 获取session里的username
    username = session.get('username', None)
    # 根据session里的username查用户表
    user = User.query.filter(User.username == username).first()
    if user:
        if user.udertype:
            utype = '普通用户'
        else:
            utype = '管理员'
    else:
        utype = ''
    # print('xixi')
    # print(hu)
    return render_template('list.html', **{
        'category': dbk,
        'id': id,
        'tz': tz,
        'dbk': dbk,
        'xbk': xbk,
        'idxbk': idxbk,
        'tzs': tzs,
        'newuser': newuser,
        'user': user,
        'utype': utype

    })


# 版块分类
@bbs.route('/index_1/<int:id>')
def index_1(id):
    # 得到指定ID大板块
    dd = BbsCategory.query.filter(BbsCategory.cid == id).all()
    # 得到指定ID小版块
    xbk = BbsCategory.query.filter(BbsCategory.classpath == id).all()
    # 所有大板块
    bz = BbsCategory.query.filter(BbsCategory.parentid == 0).all()
    # 得到最新注册用户名
    newuser = User.query.order_by(-User.uid).first()
    # 获取session里的username
    username = session.get('username', None)
    # 根据session里的username查用户表
    user = User.query.filter(User.username == username).first()
    if user:
        if user.udertype:
            utype = '普通用户'
        else:
            utype = '管理员'
    else:
        utype = ''
    return render_template('index_1.html', **{
        'bkk': dd,
        'smalls': xbk,
        'id': id,
        'category': bz,
        'newuser': newuser,
        'user': user,
        'utype': utype

    })


# 搜索
@bbs.route('/search')
def search():
    return render_template('search.html')


# 找回密码
@bbs.route('/getpass')
def getpass():
    return render_template('getpass.html')


# 退出
@bbs.route('/logout')
def logout():
    # session.pop('username')
    session.clear()
    return redirect(url_for('bbs.index'))
    # return render_template('login.html', msg='您已退出站点，现在将以游客身份转入退出前页面', ht='')


# 立即注册
@bbs.route('/reg')
def reg():
    return render_template('reg.html')


# 提交注册
@bbs.route('/zhuce', methods=['GET', 'POST'])
def zhuce():
    if request.method == 'GET':
        return render_template('login.html', msg='走错路了', ht='')
    else:
        username = request.form.get('username', None)
        # print(username)
        password = request.form.get('password', None)
        # print(password)  # ''  None
        repassword = request.form.get('repassword')
        phone = request.form.get('phone')

        if username and password and repassword and phone:
            # a = re.search(r'\d{6,12}[a-z]*',password)
            a = re.search(r'(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{6,12}$',password)
            b = re.search(r'\d{6,11}',phone)
            print('aaaaaaaaaaaaaaaaaaaaa')
            print(a)
            if b:
                if a:
                    if password == repassword:
                        user = User.query.filter(User.username == username).first()
                        # phone = User.query.filter(User.phone==phone).first()
                        if not user:
                            # 注册
                            user = User()
                            user.username = username
                            hash_password = generate_password_hash(password)
                            user.password = hash_password
                            user.phone = phone

                            flag = user.save()
                            if flag:
                                session['username'] = username

                                return redirect(url_for('bbs.index'))
                        else:
                            # 用户已经注册
                            return render_template('login.html', msg='此用户名或手机号已被占用', ht='reg')
                    else:
                        # 密码不一致
                        return render_template('login.html', msg='密码不一致', ht='reg')
                else:
                    return render_template('login.html', msg='密码为6-12位，不能只为数字，', ht='reg')
            else:
                return render_template('login.html', msg='电话号格式不正确，', ht='reg')
        else:
            return render_template('login.html', msg='必须输入用户名或者密码', ht='reg')


# 登录
@bbs.route('/denglu', methods=['POST', 'GET'])
def denglu():
    if request.method == 'GET':
        return render_template('login.html', msg='走错路了', ht='')
    else:
        username = request.form.get('username', None)
        password = request.form.get('password', None)

        if username and password:
            user = User.query.filter(User.username == username).first()
            # print(user)
            if user:
                result = check_password_hash(user.password, password)
                if result:
                    # 服务器保存 session 当成字典
                    session['username'] = username

                    return redirect(url_for('bbs.index'))

                else:
                    return render_template('login.html', msg='用户名或者密码错误', ht='')
            else:
                return render_template('login.html', msg='没有此用户', ht='')
        else:
            return render_template('login.html', msg='必须输入用户名或者密码', ht='')


# 判断发帖有没有登陆
@bbs.route('/fatie/<int:id>')
def fatie(id):
    username = session.get('username', None)
    if username is None:
        return render_template('register.html', id=id)
    return redirect(url_for('bbs.addc', id=id))


# 发帖登录
@bbs.route('/ftdl/<int:id>', methods=['POST', 'GET'])
def ftdl(id):
    if request.method == 'GET':
        return render_template('login.html', msg='走错路了', ht='')
    else:
        username = request.form.get('username', None)
        password = request.form.get('password', None)
        questionid = request.form.get('questionid')
        answer = request.form.get('answer')

        # 获取session里的username
        username = session.get('username', None)
        # 根据session里的username查用户表
        user = User.query.filter(User.username == username).first()
        if user:
            if user.udertype:
                utype = '普通用户'
            else:
                utype = '管理员'
        else:
            utype = ''
        if username and password:
            user = User.query.filter(User.username == username).first()
            # print(user)
            if user:
                result = check_password_hash(user.password, password)
                if result:
                    user.problem = questionid
                    user.result = answer
                    flag = user.save()
                    if flag:
                        session['username'] = username

                        return redirect(url_for('bbs.addc', id=id))
                    return '错误'
                else:
                    return render_template('login.html', msg='用户名或者密码错误', ht='ftdl/' + 'id', user=user, utype=utype)
            else:
                return render_template('login.html', msg='没有此用户', ht='ftdl/' + 'id', user=user, utype=utype)
        else:
            return render_template('login.html', msg='必须输入用户名,密码或者密保', ht='ftdl/' + 'id', user=user, utype=utype)


# 发帖页面
@bbs.route('/addc/<int:id>')
def addc(id):
    # 大板块
    bz = BbsCategory.query.filter(BbsCategory.parentid == 0).all()
    # 取对应小版块的大版块
    idxbk = BbsCategory.query.filter(BbsCategory.cid == id).all()
    username = session.get('username', None)
    # 根据session里的username查用户表
    user = User.query.filter(User.username == username).first()
    if user:
        if user.udertype:
            utype = '普通用户'
        else:
            utype = '管理员'
    else:
        utype = ''

    return render_template('addc.html', **{
        'category': bz,
        'id': id,
        'idxbk': idxbk,
        'user': user,
        'utype': utype
    })


# 发帖提交
@bbs.route('/posted/<int:id>', methods=['POST', 'GET'])
def posted(id):
    if request.method == 'GET':
        return redirect(url_for('bbs.addc', id=id))
    else:
        # 获取session里的username
        username = session.get('username', None)
        # 根据session里的username查用户表
        user = User.query.filter(User.username == username).first()
        if user:
            if user.udertype:

Xforum/templates/addc.html
{% extends 'index.html' %}
{% block yangshi %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='index/css/post.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='index/css/style.css') }}"/>
    <style>
        #textbox{
            width: 600px;
            height: 200px;
        }
    </style>
{% endblock %}
{% block index %}
    <div id="wp" class="wp">
        <div id="pt" class="bm cl">
            <div class="z"><a href="./" class="nvhm" title="发表帖子内核源码 - 10分钟学院">发表帖子内核源码 - 10分钟学院</a><em>&raquo;</em><a
                    href="{{ url_for('bbs.index') }}">论坛</a><em>&raquo;</em><a
                    href="{{ url_for('bbs.index_1',id = id) }}">PHP技术交流</a><em>&raquo;</em><a
                    href="{{ url_for('bbs.list',id=id ) }}">{{ idxbk[0].classname }}</a><em>&raquo;</em>发表帖子
            </div>
        </div>
        <form method="post" autocomplete="off" id="postform" action="{{ url_for('bbs.posted',id =id) }}" >
            <div id="ct" class="ct2_a ct2_a_r wp cl" >
                <div class="mn">
                    <div class="bm bw0 cl" id="editorbox">
                        <ul class="tb cl mbw">
                            <li class="a"><a href="javascript:;">发表帖子</a></li>
                        </ul>

                        <div id="postbox">
                            <div class="pbt cl">
                                <div class="z">
                                    <span><input type="text" name="title" id="subject" class="px"
                                                 onkeyup="showLength(this,'checklen',80);" style="width: 25em"
                                                 tabindex="1"/></span>
                                    <span id="subjectchk">还可输入 <strong id="checklen">80</strong> 个字符</span>
                                </div>
                            </div>

                            <div id="e_body_loading" >

{#                                <script id="container" name="content" type="text/plain">#}
{##}
{#                                </script>#}
{#                                <!-- 配置文件 -->#}
{#                                <script type="text/javascript" src="../static/index/textbox/ueditor.config.js"></script>#}
{#                                <!-- 编辑器源码文件 -->#}
{#                                <script type="text/javascript" src="../static/index/textbox/ueditor.all.js"></script>#}
{#                                <!-- 实例化编辑器 -->#}
{#                                <script type="text/javascript">#}
{#                                    var ue = UE.getEditor('container');#}
{#                                </script>#}
                                <textarea name="textbox" id="textbox"></textarea>

                            </div>

                            <div id="post_extra" class="ptm cl">
                                <div id="post_extra_tb" class="cl" onselectstart="return false">
                                    <label id="extra_price_b" class="a" onclick="showExtra('extra_price')"><span
                                            id="extra_price_chk">售价</span></label>
                                </div>

                                <div id="post_extra_c">
                                    <div id="extra_price_c" class="exfm cl">
                                        售价:<input type="text" id="price" name="price" class="px pxs"
                                                  onblur="extraCheck(2)" value="0"/> 金钱<span class="xg1">(最高 30 )</span>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" id="classid" name="classid" value="5"/>

                            <div class="mtm mbm pnpost">
                                <button type="submit" id="postsubmit" class="pn pnc" value="true" name="topicsubmit">
                                    <span>发表帖子</span>
                                </button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </form>

        <script>

            var BROWSER = {};
            var USERAGENT = navigator.userAgent.toLowerCase();
            browserVersion({
                'ie': 'msie',
                'firefox': '',
                'chrome': '',
                'opera': '',
                'safari': '',
                'mozilla': '',
                'webkit': '',
                'maxthon': '',
                'qq': 'qqbrowser'
            });
            if (BROWSER.safari) {
                BROWSER.firefox = true;
            }
            BROWSER.opera = BROWSER.opera ? opera.version() : 0;

            function showLength(obj, checklen, maxlen) {

                var v = obj.value, charlen = 0, maxlen = !maxlen ? 200 : maxlen, curlen = maxlen, len = strlen(v);
                for (var i = 0; i < v.length; i++) {
                    if (v.charCodeAt(i) < 0 || v.charCodeAt(i) > 255) {
                        curlen -= 2;
                    }
                }
                if (curlen >= len) {
                    document.getElementById("checklen").innerHTML = curlen - len;
                } else {
                    obj.value = mb_cutstr(v, maxlen, true);
                }

            }

            function strlen(str) {
                return (BROWSER.ie && str.indexOf('\n') != -1) ? str.replace(/\r?\n/g, '_').length : str.length;
            }

            function mb_cutstr(str, maxlen, dot) {
                var len = 0;
                var ret = '';
                var dot = !dot ? '...' : '';
                maxlen = maxlen - dot.length;
                for (var i = 0; i < str.length; i++) {
                    len += str.charCodeAt(i) < 0 || str.charCodeAt(i) > 255 ? 3 : 1;
                    if (len > maxlen) {
                        ret += dot;
                        break;
                    }
                    ret += str.substr(i, 1);
                }
                return ret;
            }

            function extraCheck(len) {

                strlen = document.getElementById('price').value.length;
                if (strlen > len) {
                    alert('最高 30');
                    document.getElementById('price').value = 0;
                } else {

                    if (document.getElementById('price').value > 30) {

                        alert('最高 30');
                        document.getElementById('price').value = 30;

                    }

                }

            }
        </script>
    </div>

{% endblock %}

Xforum/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>首页 - 10分钟学院</title>
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7"/>
    {% block yangshi %}
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='index/css/style.css') }}"/>
            <link rel="stylesheet" type="text/css" href="/static/index/css/home.css" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='index/css/index.css') }}"/>
    {% endblock %}
    <script type="text/javascript" src="../static/index/js/admincp.js"></script>
    <script type="text/javascript" src="../static/index/js/common.js"></script>
</head>

<body>
<!--TOP start-->
<div id="toptb" class="cl">
    <div class="wp">
        <div class="z"><a href="javascript:;" onclick="setHomepage('http://www.phpxy.com/')">设为首页</a><a
                href="javascript:;" onclick="window.external.AddFavorite(location.href,document.title);return false;">收藏本站</a>
        </div>
    </div>
</div>
<script>
    function setHomepage(sURL) {

        document.body.style.behavior = 'url(#default#homepage)';
        document.body.setHomePage(sURL);

    }
</script><!--TOP end-->

<!--HEAD start-->
<div id="hd">
    <div class="wp">
        <div class="hdc cl">
            <h2><a href="{{ url_for('bbs.index') }}" title="首页 - 10分钟学院"><img src="{{ url_for('static',filename='index/images/logo.jpg') }}"
                                                      height="80" border="0"/></a></h2>
            {% if 'username' in session %}
                <div id="um">
                    <div class="avt y"><a href="{{ url_for('bbs.home',homeid = 1) }}"><img src="{{ url_for('static',filename=user.picture) }}"></a></div>
                    <p>
                        <strong class="vwmy"><a href="{{ url_for('bbs.home',homeid = 2) }}" target="_blank">{{ user.username }}</a></strong>
                        <span class="pipe">|</span><a href="{{ url_for('bbs.home',homeid = 2) }}">设置</a>
                        {% if utype == '管理员' %}
                            <span class="pipe">|</span><a href="{{ url_for('admin.login') }}" target="_blank">管理中心</a>
                        {% else %}
                        {% endif %}
                        <span class="pipe">|</span><a href="{{ url_for('bbs.logout') }}">退出</a>
                    </p>
                    <p>
                        <a id="extcreditmenu" href="#">积分: {{ user.grade }}</a>
                        <span class="pipe">|</span>用户权限: {{ utype }} </p>
                </div>
            {% else %}
                <form method="post" autocomplete="off" id="lsform" action="{{ url_for('bbs.denglu') }}">
                    <div class="fastlg cl">
                        <div class="y pns">
                            <table cellspacing="0" cellpadding="0">
                                <tr>
                                    <td><span class="ftid">用户名</span></td>
                                    <td><input type="text" name="username" placeholder="输入用户名" id="ls_username"
                                               autocomplete="off"
                                               class="px vm"/></td>
                                    <td class="fastlg_l">
                                        <label for="ls_cookietime"><input type="checkbox" name="cookietime"
                                                                          id="ls_cookietime" class="pc"
                                                                          value="true"/>自动登录</label>
                                    </td>
                                    <td>&nbsp;<a href="{{ url_for('bbs.getpass') }}">找回密码</a></td>
                                </tr>
                                <tr>
                                    <td><label for="ls_password" class="z psw_w">密码</label></td>
                                    <td><input type="password" name="password" id="ls_password" class="px vm"
                                               autocomplete="off"/></td>
                                    <td class="fastlg_l">
                                        <button type="submit" class="pn vm" name="loginsubmit" value="true"
                                                style="width:75px;"><em>登录</em></button>
                                    </td>
                                    <td>&nbsp;<a href="{{ url_for('bbs.reg') }}" class="xi2 xw1">立即注册</a></td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>

        <div id="nv">
            <ul>
                <li class="a" id="mn_forum"><a href="{{ url_for('bbs.index') }}" hidefocus="true"
                                               title="10分钟学院">首页</a><span>10分钟学院</span></li>
                {% for dbk in category %}
                    <li id="mn_home"><a href="{{ url_for('bbs.index_1',id=dbk.cid) }}" hidefocus="true"
                                        title="Space">{{ dbk.classname }}</a></li>

                {% endfor %}
            </ul>
        </div>

        <div id="scbar" class="cl">
            <form id="scbar_form" method="post" autocomplete="off" action="{{ url_for('bbs.sousuo') }}" target="_blank">
                <table cellspacing="0" cellpadding="0">
                    <tr>
                        <td class="scbar_icon_td"></td>
                        <td class="scbar_txt_td"><input type="text" name="keywords" id="scbar_txt"
                                                        onfocus="if(this.value=='请输入搜索内容'){this.value='';this.style.color='#666';}"
                                                        onblur="if(this.value==''){this.value='请输入搜索内容';this.style.color='#ccc';}"
                                                        value="请输入搜索内容" style="color:#CCCCCC" autocomplete="off"/></td>
                        <td class="scbar_btn_td">
                            <button type="submit" name="searchsubmit" id="scbar_btn" class="pn pnc" value="true"><strong
                                    class="xi2 xs2">搜索</strong></button>
                        </td>
                        <td class="scbar_hot_td">
                            <div id="scbar_hot">
                                <strong class="xw1">热搜: </strong>
                                <a href="{{ url_for('bbs.search') }}" target="_blank" class="xi2">活动</a>
                                <a href="{{ url_for('bbs.search') }}" target="_blank" class="xi2">交友</a>
                                <a href="{{ url_for('bbs.search') }}" target="_blank" class="xi2">教程</a>
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>




{% block index %}
    <div id="wp" class="wp">
        <div id="pt" class="bm cl">
            <div class="z">
                <a href="{{ url_for('bbs.index') }}" class="nvhm" title="首页 - 10分钟学院">首页 - 10分钟学院</a><em>&raquo;</em><a
                    href="{{ url_for('bbs.index') }}">论坛</a>
            </div>
            <div class="z"></div>
        </div>

        <div id="ct" class="wp cl">
            <div id="chart" class="bm bw0 cl">
                <div class="y">
                    <p class="chart z">
                        帖子: <em>{{ numbertz }}</em><span class="pipe">|</span>
                        会员: <em>{{ number }}</em><span class="pipe">|</span>
                        欢迎新会员: <em>{{ newuser }}</em>
                    </p>
                </div>
            </div>

            <div class="mn">
                <div class="fl bm">
                    <!--板块 start-->
                    {% for bk in category %}
                        {#     parentid是0的是大版块               #}
                        {% if bk.parentid == 0 %}
                            <div class="bm bmw  cl">
                                <div class="bm_h cl">
                                    <h2><a href="{{ url_for('bbs.index_1',id=bk.cid) }}">{{ bk.classname }}</a></h2>
                                </div>

                                {% for small in smalls %}
                                    {% if small.classpath == bk.cid %}
                                        <div id="category_1" class="bm_c">
                                            <table cellspacing="0" cellpadding="0" class="fl_tb">
                                                <tr>
                                                    <td class="fl_icn">
                                                        <a href="{{ url_for('bbs.list',id= small.cid ) }}"><img
                                                                src="{{ url_for('static',filename='index/images/forum.gif') }}"
                                                                alt="内核源码"/></a>
                                                    </td>
                                                    <td>
                                                        <h2><a href="{{ url_for('bbs.list',id= small.cid ) }}"
                                                               style="color:">{{ small.classname }}</a></h2>
                                                        <p class="xg2"></p>
                                                        <p>版主: <span class="xi2">{{ small.compere }}</span></p>
                                                    </td>
                                                    <td class="fl_i">
                                                        <span class="xi2">17</span><span class="xg1"> / 15</span>
                                                    </td>
                                                    <td class="fl_by">
                                                        <div>
                                                            <a href="" class="xi2">sfsdfsdfsd</a>
                                                            <cite><span
                                                                    title="2019-06-11">1天前</span> admin</cite></div>
                                                    </td>
                                                </tr>

                                            </table>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endfor %}

                    <div class="bm bmw  cl">
                        <div class="bm_h cl">
                            <h2><a href=""></a></h2>
                        </div>
                        <div id="category_1" class="bm_c">
                            <table cellspacing="0" cellpadding="0" class="fl_tb">
                            </table>
                        </div>
                    </div>
                    <!--板块 end-->
                </div>

                <div class="bm lk">
                    <div id="category_lk" class="bm_c ptm">
                        <ul class="m mbn cl">
                            <li class="lk_logo mbm bbda cl">
                                <img src="../static/index/images/logo_88_31.gif" border="0" alt="官方论坛"/>
                                <div class="lk_content z">
                                    <h5><a href="http://www.discuz.net" target="_blank">官方论坛</a></h5>
                                    <p>提供最新 Discuz! 产品新闻、软件下载与技术交流</p>
                                </div>
                        </ul>

                        <ul class="x mbm cl">
                            <li><a href="http://www.baidu.com" target="_blank" title="百度">百度</a></li>
                            <li><a href="http://www.sina.com/" target="_blank" title="漫游平台">漫游平台</a></li>
                            <li><a href="http://www.163.com/" target="_blank" title="Yeswan">Yeswan</a></li>
                            <li><a href="http://www.5d6d.com/" target="_blank" title="我的领地">我的领地</a></li>
                        </ul>
                    </div>
                </div>


            </div>
        </div>
    </div>
    <!--CONTENT end-->
{% endblock %}
<!--FOOT start-->
<div id="ft" class="wp cl">
    <div id="flk" class="y">
        <p>
            <a href="#">京ICP备 89273号</a><span class="pipe">|</span><strong><a href="http://www.phpxy.com/"
                                                                              target="_blank">phpxy</a></strong>
        </p>
        <p class="xs0">
            Time Now Is: 06-12 16:33 </p>
    </div>
    <div id="frt">
        <p>Powered by <strong><a href="http://www.phpxy.com/" target="_blank">phpxy</a></strong> <em>V2</em></p>
        <p class="xs0">&copy; 2019 <a href="http://www.phpxy.com/" target="_blank">phpxy Inc.</a></p>
    </div>
</div><!--FOOT end-->
</body>
</html>